### ISSUE TITLE
[Question] What's the second console window in the picture?

### ISSUE THREAD

**Issue by wrefgtzweve** [Python1320/valvecmd#1]
Maybe a very dumb question, sorry if it is.
I was wondering how you got the gmod.exe console window? is this a build in feature or another GitHub repo?
Thanks in advance.

![image](https://user-images.githubusercontent.com/69946827/140576768-af0ec147-2173-4ac8-ba98-4c03a63382b0.png)

**Comment by Python1320** [comment]
hl2.exe -textmode

**Comment by wrefgtzweve** [comment]
Thanks!
